### PR TITLE
[Feat] Add interactive tables for all data pages

### PR DESCRIPTION
**Pull request by chuckyroh**
## Feature addition #3 
- Add sorting by headers
- Add search input (as you type it filters the list)

### Dependency added
- Alpine js <https://github.com/alpinejs/alpine> 
  - small framework to add two way data binding

### Progress
- [x] World table
- [x] State table
- [x] India timeline table

### Screens
TableFunctions

### CODE REVIEW

**Comment by chuckyroh** [comment]
@Mustafiz04 
Not finished yet but wanted to see if this is what you were looking for. I added Alpine.js to make things easier to do and read.
I should be able to add it to the other tables fairly easily.

**Comment by chuckyroh** [comment]
Completed now. I can make adjustments to whatever if you need.

**Comment by Mustafiz04** [comment]
Conflicting files
public/js/indiacovid.js
public/js/statewise.js
public/js/worldcovid.js

Can you solve branch conflicts? and make a new pull request.

You have added all the new features that are appreciable. I will merge after solving the conflict.

Thank you. 👏

**Comment by chuckyroh** [comment]
Fixed the conflict. Doesn't need those get() statements anymore for those files.

**Comment by Mustafiz04** [comment]
Great work.!! 👏👏

**Comment by chuckyroh** [comment]
Thanks!

**Pull request merged**
